### ISSUE TITLE
Add support for drafts

### ISSUE THREAD

**Issue by marcusolsson** [marcusolsson/edith#10]
Allow authors work on new content without blocking changes to content that's already been published.

**Suggestion**:

Add a `draft` property to the front matter. If set to `true`, content will be visible during development, but hidden in production.

```
---
draft: true
---
```

**Comment by eleijonmarck** [comment]
One could have it the other way around stating published instead.

```
published: true
```

Have seen both approaches from things like Hugo, Gatsby and gridsome

**Comment by marcusolsson** [comment]
Everyone will publish content, but not everyone is going to create drafts. I like `draft` because it's an opt-in feature. It assumes content is published by default. 

Also, a `published` flag will never go away, unless you want to take down the content.

I assume the motivation behind a `published` flag, is to encourage working with drafts, but it does add to the cognitive load to somewhere learning Edith. I imagine there's going to be a few "Why's my tutorial not showing up?", because they didn't read the documentation.

**Comment by eleijonmarck** [comment]
Now that is what I call experience. Great point.

**Comment by marcusolsson** [comment]
Thanks for suggesting an alternative solution, and for challenging me to explain it 👍
