### ISSUE TITLE
Add support for math

### ISSUE THREAD

**Issue by marcusolsson** [marcusolsson/edith#11]
Edith should support writing math equations in modules:

For example:

```
Lift($L$) can be determined by Lift Coefficient ($C_L$) like the following equation.

$$
L = \frac{1}{2} \rho v^2 S C_L
$$
```

would generate something like:

<img width="986" alt="screenshot" src="https://user-images.githubusercontent.com/8396880/78349666-3d321480-75a4-11ea-8a86-bfe58a89a9ca.png">

There seems to be a remark plugin for this: https://github.com/remarkjs/remark-math that we should look at.

**Comment by tskarhed** [comment]
This is awesome! 😄
