### ISSUE TITLE
"How to use" in README

### ISSUE THREAD

**Issue by tskarhed** [marcusolsson/edith#13]
Gatsby noob here - do I use it as a theme or how do I approach this? Or is it a starter?

**Comment by marcusolsson** [comment]
It's a starter at this point. I'm a Gatsby noob myself so still learning here, but I think this is something I'll be looking at next: https://www.gatsbyjs.org/docs/themes/

**Comment by marcusolsson** [comment]
Added instructions to the README, and create #15. Thanks!
