### ISSUE TITLE
Style and margin for blockquote

### ISSUE THREAD

**Issue by tskarhed** [marcusolsson/edith#17]
![image](https://user-images.githubusercontent.com/1438972/78499295-144e8280-7750-11ea-954d-e1c7874ed39e.png)
The margin-bottom for the paragraph inside should be 0. 

Maybe a personal preference, but should it also be cursive? I like the style Medium uses for their blockquotes.

**Comment by marcusolsson** [comment]
Thanks for the heads-up! Should look better now 👍
