### ISSUE TITLE
How are folders handled?

### ISSUE THREAD

**Issue by tskarhed** [marcusolsson/edith#21]
The content folder quickly gets cluttered, so folders are necessary. How are these supposed to be handled? At the moment they can be seen in the URL. If a course is in a folder, how do I reference the modules properly?

**Comment by marcusolsson** [comment]
I don't have a good answer for this yet. I want to offer the freedom to organize your content in a way that makes sense for you, so folders should definitely be supported.

My thoughts so far have been to treat folders as namespaces. I guess the other way would be to flatten all folders when generating the site. That way you couldn't use the same slug even if they were in two different folders.
