### ISSUE TITLE
Add support for quizzes

### ISSUE THREAD

**Issue by marcusolsson** [marcusolsson/edith#3]
Modules should have a way to let the learner reinforce what they've just learned. 

The educator should be able to define simple forms with inputs like:

- Text fields
- Radio buttons
- Checkboxes

There seems to be some ideas around defining forms in Markdown, such as:

```
Name: ___

Favorite animal:
- ( ) Cat
- ( ) Dog

Competencies:
- [ ] Programming
- [ ] Public speaking
```

Another solution would be to import a Quiz JSX component with MDX.

```
## Test your skills

Put what you've learned to the test:

<Quiz>
  <RadioGroup>
    <FormControlLabel value="cat" control={<Radio />} label="Cat" />
    <FormControlLabel value="dog" control={<Radio />} label="Dog" />
  </RadioGroup>
</Quiz>
```

**Comment by tskarhed** [comment]
JSX should probably be used sparingly, although it opens up a lot of possibilities. Not sure who the target group is - do they know how to use JSX? If not, maybe a minimal component would suffice, that parses the children:

```jsx
<Quiz>
Name: ___

Favorite animal:
- ( ) Cat
- ( ) Dog

Competencies:
- [ ] Programming
- [ ] Public speaking
</Quiz>
```

**Comment by marcusolsson** [comment]
Usability is definitely a concern here. 

Ideally, I'd like to go for pure Markdown, which could mean writing a [Remark plugin](https://github.com/remarkjs/remark/blob/master/doc/plugins.md) to generate a HTML form.

Though JSX does open up a lot of possibilities like you say. For example, I think JSX could help with #1, and possibly other interactive building blocks for modules.

In the future, I'd like to see a graphical CMS to help building more complex modules.

**Comment by marcusolsson** [comment]
Discovered this text format called [GIFT](https://docs.moodle.org/38/en/GIFT_format). Seems to have relatively wide adoption.

Basically lets you define a multi-choice quiz like this:

```gift
::Grants tomb::Who is buried in Grant's tomb in New York City? {
=Grant
~No one
#Was true for 12 years, but Grant's remains were buried in the tomb in 1897
~Napoleon
#He was buried in France
~Churchill
#He was buried in England
~Mother Teresa
#She was buried in India
}
```

The equals sign marks the right answer, and the lines with hash tags are the responses for each answer.

The Markdown could then look something like this:

```
## Review quiz

<Quiz>
::Grants tomb::Who is buried in Grant's tomb in New York City? {
=Grant
~No one
#Was true for 12 years, but Grant's remains were buried in the tomb in 1897
~Napoleon
#He was buried in France
~Churchill
#He was buried in England
~Mother Teresa
#She was buried in India
}
</Quiz>
```
